language: python
python:
  - "2.7"
before_install:
  - pip install coveralls --use-mirrors
script: nosetests -v --with-coverage --cover-erase --cover-package=app, analysis
after_success:
  - coveralls
